wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1645202676
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 16
      4: 3.8.10
      5: 0.12.6
      8:
      - 5
actor_hidden_dim:
  desc: null
  value: 64
actor_learning_rate:
  desc: null
  value: 0.0003
batch_size:
  desc: null
  value: 32
critic_hidden_dim:
  desc: null
  value: 64
critic_learning_rate:
  desc: null
  value: 0.0003
discount_factor:
  desc: null
  value: 0.9
embedding_dim:
  desc: null
  value: 100
items_num:
  desc: null
  value: 1001
replay_memory_size:
  desc: null
  value: 1000000
state_size:
  desc: null
  value: 10
tau:
  desc: null
  value: 0.001
users_num:
  desc: null
  value: 15401
